#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage $0 script" 1>&2
    exit -1
fi

script=$1
bsub -P R:GEOPM \
     -q workq \
     -L /bin/bash \
     -W 10 \
     -J GEOPM:$script \
     -o ${script}.out \
     -e ${script}.err \
     -n 2 \
     -R "2*{select[clx2s8260L] span[ptile=1]}" \
     $script

