#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage $0 script" 1>&2
    exit -1
fi

script=$1
bsub -P R:GEOPM \
     -p workq \
     -t 30 \
     -J GEOPM:$script \
     -o ${script}.out \
     -e ${script}.err \
     -C clx2s8260L \
     -N 2 \
     -l MSRSAFE=1 \
     $script
