GEOPM_CFLAGS="-I$GEOPM_INC"
GEOPM_LDFLAGS="-L$GEOPM_LIB -lgeopm"
OMP_FLAGS="-fopenmp"

make \
CC=icc CXX=icpc \
MPICC=mpiicc MPICXX=mpiicpc \
CFLAGS="$GEOPM_CFLAGS $OMP_FLAGS -DTUTORIAL_ENABLE_MKL -D_GNU_SOURCE -std=c99 -xAVX $CFLAGS" \
CXXFLAGS="$GEOPM_CFLAGS $OMP_FLAGS -DTUTORIAL_ENABLE_MKL -D_GNU_SOURCE -std=c++11 -xAVX $CXXFLAGS" \
LDFLAGS="$GEOPM_LDFLAGS $OMP_FLAGS -lm -lrt -mkl -xAVX $LDFLAGS"
